CREATE TABLE IF NOT EXISTS resources (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  origin VARCHAR(2048) NOT NULL,
  code VARCHAR(10) NOT NULL,
  date_created DATETIME NOT NULL DEFAULT NOW(),
  last_access DATETIME NOT NULL DEFAULT NOW(),
  active BOOLEAN NOT NULL DEFAULT 1,
  deleted BOOLEAN NOT NULL DEFAULT 0
);
